### ISSUE TITLE
Having trouble converting labelbox to darknet

### ISSUE THREAD

**Issue by bkeefe313** [ultralytics/JSON2YOLO#4]
I have a dataset I labeled and exported from labelbox. I found this repo trying to find an easy way to convert the data to Darknet format, and I'm having some issues.

For starters, I specified that I was using labelbox and the filepath to my data ([here](https://github.com/ultralytics/JSON2YOLO/files/4120403/export-2020-01-27T15_38_47.966Z.json.zip)).
```
if __name__ == '__main__':
    source = 'labelbox'

    if source is 'labelbox':  # Labelbox https://labelbox.com/
        convert_labelbox_json(name='darknet',
                              file='../myfile.json')
```

I ran the script with `python run.py` and have been getting errors caused by the format of the file itself. My data is actually a list (that is, all the json is enclosed within "[]"), so I got 
`TypeError: list indices must be integers, not str`
Understandable. I enclosed the entire loop for writing images within a loop that went through the whole list of json dicts.

```
with open(file) as f:
        data = json.load(f)

# Write images and shapes
name = 'out' + os.sep + name
file_id, file_name, width, height = [], [], [], []
for j in data:
    for i, x in enumerate(tqdm(j['images'], desc='Files and Shapes')):
        file_id.append(x['id'])
        file_name.append('IMG_' + x['file_name'].split('IMG_')[-1])
        width.append(x['width'])
        height.append(x['height'])

        # filename
        with open(name + '.txt', 'a') as file:
            file.write('%s\n' % file_name[i])

        # shapes
        with open(name + '.shapes', 'a') as file:
        file.write('%g, %g\n' % (x['width'], x['height']))


```

Then there was a whole host of new issues because the naming within the json isn't consistent with the script. I don't know if labelbox changed the format of their data exports or if I made some glaring mistake somewhere, but it feels like I would have to essentially rewrite the entire script to get this to work correctly.

**Comment by danielkangell** [comment]
I think labelbox must have changed their json export structure, because I had the same issues you had. This repo seems to kind of work when using Labelbox's coco-exporter to change their export to coco formatting, but I'm also struggling to use that. It seems as though we have to just write it ourselves? I am also a novice so might be doing something stupid, it seems crazy that this code doesn't exist somewhere...

**Comment by bkeefe313** [comment]
This was a while ago, so I may be remembering wrong, but I believe I had to ditch labelbox and relabel the whole dataset with something else. LabelImg seems to be one, although it’s not the one I used.

**Comment by danielkangell** [comment]
I think I ended up writing something in the end!

**Comment by JitskedeVries** [comment]
I adjusted it myself + created a pullrequest. It is a slightly different approach than done before. But if anyone needs it: https://github.com/JitskedeVries/JSON2YOLO

**Comment by bkeefe313** [comment]
Thanks for including a solution. Closing the thread bc it looks like the solutions are there.

**Comment by glenn-jocher** [comment]
@bkeefe313 thanks for sharing your solution, and for creating a pull request. Your efforts will be a valuable resource for others facing similar challenges. If anyone has questions or needs further assistance with the Ultralytics YOLO repos, feel free to reach out or refer to the Ultralytics Docs for guidance. Appreciate your contribution!
