### ISSUE TITLE
Unable to read images from GCP in labelbox_json2yolo.py

### ISSUE THREAD

**Issue by jchristo12** [ultralytics/JSON2YOLO#42]
The images I annotated with Labelbox are stored in a GCP bucket. When I attempt to run the script, it cannot find the images in the Labelbox `json` because the image is stored on GCS.

How can this script be used when images aren't stored locally but instead in GCP?

This is the error I see:
`[Errno 22] Invalid argument: 'gs://[bucket_name]/[folder_name]/[image_name].jpg'`

**Comment by jchristo12** [comment]
Figured this out. Solution can be found [here](https://community.labelbox.com/t/converting-labelbox-annotation-export-to-yolo-v8-pytorch/449/4?u=jchristo)

**Comment by glenn-jocher** [comment]
I'm glad to hear that you were able to find a solution. The `labelbox_json2yolo.py` script currently does not support reading images directly from GCP. However, you can manually download the images from GCP and store them locally before running the script. This way, the script will be able to locate and read the images without issues. If you have further questions or need assistance with anything else related to the YOLO repos, feel free to ask.
