### ISSUE TITLE
No .yaml file?

### ISSUE THREAD

**Issue by grandonblake** [ultralytics/JSON2YOLO#60]
Hi! I'm trying to train a YOLOv8 model through Ultralytics Hub.

My dataset is currently in a COCO format and I need it to be in the YOLO format to upload it to Ultralytics Hub.
I tried the general_json2yolo.py file for each of my train, valid, and test folders. It worked but it didn't seem to create a .yaml file automatically for the YOLO format. Is there any way to do that?

**Comment by glenn-jocher** [comment]
@grandonblake you can create the .yaml file manually by following the instructions at https://docs.ultralytics.com. The documentation provides a step-by-step guide for configuring the .yaml file for your YOLO format. Let me know if you need further assistance!

**Comment by darouwan** [comment]
@glenn-jocher Is it possible to generate the yaml file automatically? Because in projects with many classes, manually creating YAML files might lead to errors. I am happy to submit a PR.

**Comment by glenn-jocher** [comment]
Thanks for offering to submit a PR, @darouwan! Automating the creation of the .yaml file sounds like a valuable addition. Feel free to submit your PR, and we'll be happy to review it. Your contribution is appreciated!
